# pnpm-workspace.yaml
packages:
  - "docs/"
  - "tests/*"
  - "examples/*"
  - "packages/*"
  - "packages/plugins/*"
  - "packages/adapters/*"
options:
  git-checks: false
  prefer-workspace-packages: true
  strict-peer-dependencies: false
