const tldComment = `
/* =======================================================================

                THIS FILE IS AUTOMATICALLY GENERATED
    ANY CHANGES MADE TO IT WILL BE LOST IF YOU REBUILD THE SERVER!!! 

    Use the backframe admin-ui instead to modify the server behaviour
    However, you can edit it directly and not break anything as long
    as you do not rebuild the server from your backframe.json file
    
  ======================================================================= */


`;

const errorMsg = {
  msg: "An error occurred while trying to process your request",
  status: "500",
  description: "It's not you, its us. Please try again later",
};

const requireExpress = `const express = require("express")`;

const createRouter = `const router = express.Router()`;
const exportRouter = `module.exports = router`;
const authImport = `const checkAuth = require("@backframe/core")`;

module.exports = {
  tldComment,
  errorMsg,
  requireExpress,
  createRouter,
  exportRouter,
  authImport,
};
