#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/home/runner/work/backframe.js/backframe.js/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="$NODE_PATH:/home/runner/work/backframe.js/backframe.js/node_modules/.pnpm/node_modules"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../../../../prisma@4.8.1/node_modules/prisma/build/index.js" "$@"
else
  exec node  "$basedir/../../../../../../prisma@4.8.1/node_modules/prisma/build/index.js" "$@"
fi
